@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.dirtengineers.squirtgun.datagen.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;