@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.dirtengineers.squirtgun.common.entity;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;