modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="squirtgun"
version="${file.jarVersion}"
displayName="SquirtGun" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png" #optional
credits="The developers associated with Akliz Server Hosting.  Kaupenjoe's YouTube tutorials. Metric assloads of caffiene and nicotine" #optional
authors="Dirt Engineers"
description='''A gun that fires a slug made of an arbritrary liquid'''

[[dependencies.squirtgun]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.squirtgun]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.squirtgun]]
modId="chemlib"
mandatory=true
versionRange="[1.18.2-2.0.8,]"
ordering="AFTER"
side="BOTH"

[[dependencies.squirtgun]]
modId="alchemylib"
mandatory=true
versionRange="[1.0.18-2.0.8,]"
ordering="AFTER"
side="BOTH"