modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/DirtEngineers/Squirtgun/issues"

[[mods]]
    modId="squirtgun"
    version="${file.jarVersion}"
    displayName="SquirtGun"
    logoFile="logo.png" #optional
    credits="The developers associated with Akliz Server Hosting. Kaupenjoe's YouTube tutorials. Metric assloads of caffiene and nicotine"
    authors="Dirt Engineers"
    description='''A gun that fires a slug made of an arbritrary liquid'''

[[dependencies.squirtgun]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.squirtgun]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.squirtgun]]
    modId="chemlib"
    mandatory=true
    versionRange="[1.18.2-2.0.16,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.squirtgun]]
    modId="alchemylib"
    mandatory=true
    versionRange="[1.0.18-1.0.20,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.squirtgun]]
    modId="alchemistry"
    mandatory=true
    versionRange="[1.0.18-2.2.1,]"
    ordering="AFTER"
    side="BOTH"