@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.dirtengineers.squirtgun;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;