@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.dirtengineers.squirtgun.datagen.recipe.fluid_encapsulator;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;