@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package net.dirtengineers.squirtgun.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;